
find_package(PkgConfig REQUIRED)
pkg_search_module(OPENSSL REQUIRED openssl)

if(OPENSSL_FOUND)
    message(STATUS "Detecting libopenssl - done
   OPENSSL_INCLUDE_DIRS: ${OPENSSL_INCLUDE_DIRS}
   OPENSSL_LIBRARIES: ${OPENSSL_LIBRARIES}
   OPENSSL_LINK_LIBRARIES: ${OPENSSL_LINK_LIBRARIES}
   OPENSSL_VERSION: ${OPENSSL_VERSION}")
endif()
